### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by clbustos** [abscondment/statistics2#2]
Abs:

I'm currently working heavily on R and the algorithms for pdf, cdf and random number generations are better (in some cases) than statistics2
Why don't we integrate the best of this package and more methods on a new statistics3 package? On Distribution package, I try to implement all methods on pure Ruby, with a cleaner interface. statistics3 could be a pure C extension package, with new implementations for current methods, when needed, and new distributions, like Kolmogorov and others.

Tell me what you think. We can ride off the old ruby code and concentrate on do a better extension.

Greetings.

**Comment by abscondment** [comment]
I think this is a good idea. Since I'm not the original author of statistics2, I like the idea of forking it to make big changes.

It would be good to try to make it compatible with JRuby & others. So, we may want to have a slow, pure implementation and a fast C replacement, with identical tests for both. We could even do a native Java extension for JRuby.

I'm pretty swamped right now, so I don't think I'll be able to do much work right now. I can probably help with the Java stiff in the future. But for now we could either a) create a separate project or b) add you as a collaborator to the existing one so you can commit there.

What do you think?

**Comment by clbustos** [comment]
Distribution could be the wrapper for ruby, C and java version. Has test for all methods and distributions.
I prefer option a), with a compatibility layer for statistics2 to allow old user to move faster.
We call the new C/Java extension statistics3 or something like cdistribution?

**Comment by abscondment** [comment]
I think statistics3 would make sense only if there isn't overlap with the functions in statistics2. If the new library can be a replacement, it should probably have a new name scheme.
